import { useMemo, useState, useEffect } from 'react'
import {
    FileText, Download, Copy, Package, CheckCircle,
    MapPin, Ambulance, Phone, Activity, RefreshCw, X
} from 'lucide-react'
import type { Case } from '../types'

interface Props {
    cases: Case[]
}

export default function ReportsSupply({ cases }: Props) {
    const [toast, setToast] = useState<{ message: string; id: number } | null>(null)

    const showToast = (message: string) => {
        setToast({ message, id: Date.now() })
    }

    useEffect(() => {
        if (toast) {
            const timer = setTimeout(() => setToast(null), 2500)
            return () => clearTimeout(timer)
        }
    }, [toast])

    // ============================================
    // SECTION 1: AUTO-GENERATED REPORT LOGIC
    // ============================================
    const reportData = useMemo(() => {
        const now = Date.now()
        const last24h = cases.filter(c => (now - new Date(c.created_at).getTime()) <= 86400000)

        const criticalCases = last24h.filter(c => c.triage_level === 'CRITICAL')
        const urgentCases = last24h.filter(c => c.triage_level === 'URGENT')
        const routineCases = last24h.filter(c => c.triage_level === 'ROUTINE')

        const activeWorkers = new Set(last24h.filter(c => c.worker_id).map(c => c.worker_id)).size

        // Most common complaint
        const complaints: Record<string, number> = {}
        let topComplaint = 'None'
        let maxC = 0
        last24h.forEach(c => {
            if (c.chief_complaint) {
                const comp = c.chief_complaint.toLowerCase().trim()
                complaints[comp] = (complaints[comp] || 0) + 1
                if (complaints[comp] > maxC) { maxC = complaints[comp]; topComplaint = comp }
            }
        })

        // Outbreaks
        const villages: Record<string, number> = {}
        last24h.forEach(c => {
            if (c.village && (c.triage_level === 'CRITICAL' || c.triage_level === 'URGENT')) {
                villages[c.village] = (villages[c.village] || 0) + 1
            }
        })
        const outbreaks = Object.entries(villages).filter(([, count]) => count >= 2).map(([v]) => v)

        const criticalVillages = Array.from(new Set(criticalCases.map(c => c.village).filter(Boolean)))

        let actions = ""
        if (criticalCases.length > 3) actions = "Immediate deployment of rapid medical response team recommended to affected villages."
        else if (outbreaks.length > 0) actions = `Monitor and dispatch supplies to identified outbreak clusters: ${outbreaks.join(', ')}.`
        else actions = "Situation stable. Consolidate routine monitoring and continue scheduled ASHA worker rounds."

        const reportText = `DAILY HEALTH SURVEILLANCE REPORT — DISTRICT
Date: ${new Date().toLocaleDateString('en-IN')}
Generated by: VoiceTriageAI System
Reporting Period: Last 24 Hours

--- SUMMARY ---
Total Cases Registered: ${last24h.length}
Critical Cases: ${criticalCases.length}
Urgent Cases: ${urgentCases.length}
Routine Cases: ${routineCases.length}

--- FIELD OPERATIONS ---
Active ASHA Workers: ${activeWorkers}
Most Reported Symptom: ${topComplaint.toUpperCase()}

--- SURVEILLANCE ALERTS ---
Villages Reporting Critical Patients: ${criticalVillages.length > 0 ? criticalVillages.join(', ') : 'None'}
Identified Outbreak Clusters (2+ Severe cases): ${outbreaks.length > 0 ? outbreaks.join(', ') : 'None detected'}

--- RECOMMENDED ACTIONS ---
${actions}

[End of Report]`

        return { reportText, ...{ last24h, criticalCases, urgentCases, routineCases, activeWorkers, topComplaint, outbreaks, actions, criticalVillages } }
    }, [cases])

    const copyReport = () => {
        navigator.clipboard.writeText(reportData.reportText)
        showToast('Report copied to clipboard')
    }

    const downloadReport = () => {
        const blob = new Blob([reportData.reportText], { type: 'text/plain' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `NHM_Report_${new Date().toISOString().split('T')[0]}.txt`
        a.click()
        URL.revokeObjectURL(url)
        showToast('Report downloaded successfully')
    }

    // ============================================
    // SECTION 2: DRUG STOCK TRACKER
    // ============================================
    const DRUG_NAMES = [
        'ORS Packets', 'Paracetamol 500mg', 'Amoxicillin 250mg', 'Iron Folic Acid Tablets',
        'Oral Contraceptive Pills', 'Vitamin A', 'Zinc Tablets', 'Cotrimoxazole', 'Misoprostol', 'Chlorhexidine'
    ]
    const [drugs] = useState(() =>
        DRUG_NAMES.map(name => ({
            name,
            stock: Math.floor(Math.random() * (200 - 10 + 1)) + 10,
            lastRestock: new Date(Date.now() - Math.floor(Math.random() * 30) * 86400000).toLocaleDateString('en-IN')
        })).sort((a, b) => a.stock - b.stock)
    )

    const requestRestock = (drugName: string) => {
        showToast(`Restock request for ${drugName} dispatched to central PHC.`)
    }

    // ============================================
    // SECTION 3: AMBULANCE TRACKER
    // ============================================
    const [ambulances, setAmbulances] = useState([
        { id: 'AMB-001', status: 'Available', location: 'Vadapalani PHC', lastUpdated: '10m ago' },
        { id: 'AMB-002', status: 'Dispatched', location: 'En route to Tambaram', lastUpdated: '2m ago' },
        { id: 'AMB-003', status: 'Available', location: 'Perambur PHC', lastUpdated: '1h ago' },
        { id: 'AMB-004', status: 'Maintenance', location: 'District HQ', lastUpdated: '1d ago' },
    ])

    const dispatchAmbulance = (id: string) => {
        setAmbulances(prev => prev.map(a => a.id === id ? { ...a, status: 'Dispatched', location: 'Dispatching...', lastUpdated: 'just now' } : a))
        showToast(`Ambulance ${id} successfully dispatched.`)
    }

    // ============================================
    // SECTION 4: PHC LOAD SUMMARY
    // ============================================
    const PHCS = ['Vadapalani PHC', 'Tambaram PHC', 'Perambur PHC', 'Ambattur PHC', 'Avadi PHC']
    const phcLoads = useMemo(() => {
        const currentHour = new Date().getHours()
        const isOpen = currentHour >= 8 && currentHour < 20

        return PHCS.map(name => {
            const vLimit = name.replace(' PHC', '').toLowerCase()
            const relatedCases = cases.filter(c => c.village?.toLowerCase().includes(vLimit) && (Date.now() - new Date(c.created_at).getTime()) <= 86400000).length

            let load = 'Low'
            let loadColor = 'text-routine border-routine bg-routine/10'
            if (relatedCases > 8) { load = 'High'; loadColor = 'text-critical border-critical bg-critical/10' }
            else if (relatedCases > 3) { load = 'Medium'; loadColor = 'text-urgent border-urgent bg-urgent/10' }

            return {
                name,
                casesToday: relatedCases,
                load,
                loadColor,
                status: isOpen ? 'Open' : 'Closed',
                phone: `+91 9444${Math.floor(Math.random() * 900000) + 100000}`
            }
        }).sort((a, b) => b.casesToday - a.casesToday)
    }, [cases])

    return (
        <div className="flex flex-col h-full bg-[#0F1117] overflow-y-auto relative">

            {/* Toast Notification */}
            {toast && (
                <div className="fixed bottom-6 right-6 z-50 animate-in fade-in slide-in-from-bottom-4 duration-300">
                    <div className="bg-primary text-white px-4 py-3 rounded-lg shadow-xl shadow-black/50 border border-[#2DE1A8]/30 flex items-center gap-2 font-semibold text-sm">
                        <CheckCircle size={16} />
                        {toast.message}
                        <button onClick={() => setToast(null)} className="ml-4 opacity-70 hover:opacity-100 transition-opacity">
                            <X size={14} />
                        </button>
                    </div>
                </div>
            )}

            {/* HEADER */}
            <div className="flex-shrink-0 border-b border-border bg-surface px-8 py-6">
                <div className="flex items-center gap-3">
                    <FileText className="text-primary" size={28} />
                    <div>
                        <h1 className="text-2xl font-bold text-textPrimary mb-1">Reports & Supply</h1>
                        <p className="text-sm text-textSecondary">Auto-generated NHM health summaries, logistics, and resource management.</p>
                    </div>
                </div>
            </div>

            <div className="p-8 space-y-8 max-w-[1600px] mx-auto w-full">

                {/* SECTION 1: AUTO REPORT */}
                <section>
                    <div className="bg-surface border border-border rounded-xl overflow-hidden shadow-2xl">
                        <div className="bg-[#14161E] border-b border-border px-6 py-4 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                            <div className="flex items-center gap-3">
                                <FileText className="text-routine" size={20} />
                                <h2 className="text-lg font-bold text-textPrimary uppercase tracking-wide">Daily Health Surveillance Report</h2>
                            </div>
                            <div className="flex items-center gap-3 w-full md:w-auto">
                                <button onClick={copyReport} className="flex-1 md:flex-none flex items-center justify-center gap-2 bg-[#0F1117] hover:bg-border border border-border px-4 py-2 rounded-lg text-sm font-semibold text-textPrimary transition-colors">
                                    <Copy size={16} /> Copy Text
                                </button>
                                <button onClick={downloadReport} className="flex-1 md:flex-none flex items-center justify-center gap-2 bg-primary hover:bg-opacity-90 text-white px-4 py-2 rounded-lg text-sm font-semibold transition-colors">
                                    <Download size={16} /> Download .TXT
                                </button>
                            </div>
                        </div>

                        <div className="p-6 md:p-8">
                            <div className="font-mono text-sm text-textSecondary whitespace-pre-wrap leading-relaxed bg-[#0F1117] border border-border p-6 rounded-lg overflow-x-auto">
                                {reportData.reportText}
                            </div>
                        </div>
                    </div>
                </section>

                {/* CSS GRID FOR LOWER SECTIONS */}
                <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">

                    {/* SECTION 2: DRUG STOCK TRACKER (Spans 2 cols on XL) */}
                    <section className="xl:col-span-2 space-y-4">
                        <div className="flex items-center gap-2">
                            <Package className="text-textPrimary" size={20} />
                            <h2 className="text-lg font-bold text-textPrimary">District Drug & Supply Stock</h2>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {drugs.map((d, i) => {
                                const stockPct = Math.min((d.stock / 200) * 100, 100)
                                let status = 'Adequate'
                                let colorClass = 'bg-routine'
                                let textClass = 'text-routine'
                                if (d.stock < 30) { status = 'Critical Stock'; colorClass = 'bg-critical'; textClass = 'text-critical' }
                                else if (d.stock < 70) { status = 'Low Stock'; colorClass = 'bg-urgent'; textClass = 'text-urgent' }

                                return (
                                    <div key={i} className="bg-surface border border-border rounded-xl p-4 hover:border-border/80 transition-colors">
                                        <div className="flex justify-between items-start mb-3">
                                            <div>
                                                <h3 className="font-bold text-textPrimary">{d.name}</h3>
                                                <p className="text-xs text-textSecondary mt-0.5">Last restocked: {d.lastRestock}</p>
                                            </div>
                                            <div className={`text-[10px] uppercase tracking-wider font-bold px-2 py-1 rounded bg-[#0F1117] border border-border ${textClass}`}>
                                                {status}
                                            </div>
                                        </div>

                                        <div className="flex items-center gap-4 mb-3">
                                            <div className="flex-1 h-2 bg-[#0F1117] rounded-full overflow-hidden">
                                                <div className={`h-full ${colorClass} transition-all duration-1000`} style={{ width: `${stockPct}%` }} />
                                            </div>
                                            <span className="text-sm font-bold text-textPrimary w-12 text-right">{d.stock} u</span>
                                        </div>

                                        <div className="flex justify-between items-center mt-2 pt-3 border-t border-border">
                                            <span className="text-xs text-textSecondary italic">{d.stock < 70 ? 'Immediate action required' : 'Stock levels sufficient'}</span>
                                            <button
                                                onClick={() => requestRestock(d.name)}
                                                disabled={d.stock >= 70}
                                                className={`text-xs font-semibold px-3 py-1.5 rounded flex items-center gap-1 transition-colors ${d.stock < 70
                                                        ? 'bg-[#0F1117] hover:bg-surface border border-border text-primary'
                                                        : 'opacity-50 cursor-not-allowed border border-transparent text-textSecondary'
                                                    }`}
                                            >
                                                <RefreshCw size={12} /> + Restock
                                            </button>
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                    </section>

                    {/* RIGHT COLUMN: AMBULANCES & PHC LOAD */}
                    <div className="space-y-8">

                        {/* SECTION 4: PHC LOAD */}
                        <section className="space-y-4">
                            <div className="flex items-center gap-2">
                                <Activity className="text-textPrimary" size={20} />
                                <h2 className="text-lg font-bold text-textPrimary">PHC Network Load</h2>
                            </div>
                            <div className="bg-surface border border-border rounded-xl divide-y divide-border">
                                {phcLoads.map((phc, i) => (
                                    <div key={i} className="p-4 flex flex-col gap-2">
                                        <div className="flex justify-between items-start">
                                            <div>
                                                <h3 className="font-semibold text-textPrimary flex items-center gap-2">
                                                    {phc.name}
                                                    <span className={`w-2 h-2 rounded-full ${phc.status === 'Open' ? 'bg-routine' : 'bg-textSecondary'}`} title={phc.status} />
                                                </h3>
                                                <p className="text-xs text-textSecondary flex items-center gap-1 mt-1"><Phone size={10} /> {phc.phone}</p>
                                            </div>
                                            <div className={`text-xs font-bold px-2 py-1 rounded-md border ${phc.loadColor}`}>
                                                {phc.load} Load
                                            </div>
                                        </div>
                                        <div className="flex justify-between text-xs text-textSecondary mt-1">
                                            <span>Cases referred today:</span>
                                            <span className="font-bold text-textPrimary">{phc.casesToday}</span>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </section>

                        {/* SECTION 3: AMBULANCES */}
                        <section className="space-y-4">
                            <div className="flex items-center gap-2">
                                <Ambulance className="text-textPrimary" size={20} />
                                <h2 className="text-lg font-bold text-textPrimary">Fleet Management</h2>
                            </div>
                            <div className="bg-surface border border-border rounded-xl overflow-hidden">
                                {ambulances.map((amb, i) => {
                                    const isAvail = amb.status === 'Available'
                                    const color = amb.status === 'Available' ? 'text-routine' : amb.status === 'Dispatched' ? 'text-urgent' : 'text-critical'
                                    return (
                                        <div key={i} className="p-4 border-b border-border last:border-0 bg-surface hover:bg-surfaceLight transition-colors">
                                            <div className="flex justify-between items-start mb-2">
                                                <div className="flex items-center gap-2">
                                                    <Ambulance size={16} className={color} />
                                                    <span className="font-bold text-textPrimary uppercase">{amb.id}</span>
                                                </div>
                                                <span className={`text-[10px] font-bold uppercase tracking-wider ${color}`}>• {amb.status}</span>
                                            </div>
                                            <div className="text-xs text-textSecondary flex items-start gap-1 mb-3">
                                                <MapPin size={12} className="shrink-0 mt-0.5" />
                                                <span className="line-clamp-1">{amb.location}</span>
                                            </div>
                                            <div className="flex justify-between items-center text-xs">
                                                <span className="text-textSecondary italic">Upd. {amb.lastUpdated}</span>
                                                {isAvail ? (
                                                    <button
                                                        onClick={() => dispatchAmbulance(amb.id)}
                                                        className="bg-primary/10 hover:bg-primary border border-primary text-primary hover:text-white px-3 py-1 rounded transition-colors font-semibold"
                                                    >
                                                        Dispatch
                                                    </button>
                                                ) : (
                                                    <span className="px-3 py-1 border border-border bg-[#0F1117] text-textSecondary rounded opacity-50 cursor-not-allowed font-semibold">
                                                        Unavailable
                                                    </span>
                                                )}
                                            </div>
                                        </div>
                                    )
                                })}
                            </div>
                        </section>

                    </div>
                </div>

            </div>
        </div>
    )
}
